/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kikijoli.exotondeuse.ui;

import com.kikijoli.exotondeuse.exception.EmptyLineException;
import com.kikijoli.exotondeuse.exception.MowerCommandException;
import com.kikijoli.exotondeuse.exception.MowerInitializationException;
import com.kikijoli.exotondeuse.exception.SizeNotValidException;
import com.kikijoli.exotondeuse.manager.CommandManager;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Arthur JOSSEAU
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new com.kikijoli.exotondeuse.ui.MainPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaCommand = new javax.swing.JTextArea();
        executeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ma tondeuse que j'aime");
        setMinimumSize(new java.awt.Dimension(700, 300));

        javax.swing.GroupLayout mainpanelLayout = new javax.swing.GroupLayout(mainpanel);
        mainpanel.setLayout(mainpanelLayout);
        mainpanelLayout.setHorizontalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );
        mainpanelLayout.setVerticalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );

        getContentPane().add(mainpanel, java.awt.BorderLayout.CENTER);

        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 100));
        jPanel3.setPreferredSize(new java.awt.Dimension(250, 100));
        jPanel3.setLayout(new java.awt.BorderLayout());

        textAreaCommand.setColumns(20);
        textAreaCommand.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        textAreaCommand.setRows(5);
        textAreaCommand.setText("5 5\n1 2 N\nGAGAGAGAA\n3 3 E\nAADAADADDA");
        jScrollPane2.setViewportView(textAreaCommand);

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        executeBtn.setText("Execute");
        executeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeBtnActionPerformed(evt);
            }
        });
        jPanel3.add(executeBtn, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel3, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void executeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeBtnActionPerformed
        try {
            CommandManager.analyze(textAreaCommand.getText());
        } catch (EmptyLineException | SizeNotValidException | MowerInitializationException | MowerCommandException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_executeBtnActionPerformed

    public MainPanel getMainPanel() {
        return mainpanel;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton executeBtn;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private com.kikijoli.exotondeuse.ui.MainPanel mainpanel;
    private javax.swing.JTextArea textAreaCommand;
    // End of variables declaration//GEN-END:variables
}
